version: '3.8'
services:
  pulsar:
    image: apachepulsar/pulsar-all
    ports: 
      - "8080:8080"
      - "6650:6650"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
    healthcheck: 
      test: ["CMD", "pulsar-admin", "brokers", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      restart_policy:
        condition: on-failure

  cassandra:
    build: ./infrastructure/cassandra/src/
    # image: cassandra:latest
    environment:
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
    ports: 
      - "7000:7000"
      - "9042:9042"
    healthcheck: 
      test: ["CMD", "cqlsh", "-e", "'show host'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  
  data: 
    build: ./data/
    environment:
      - PULSAR_HOST=pulsar
      - TOPIC_NAME=in
      - NAMESPACE_NAME=default
      - INTERVAL_MILS=5000
    deploy:
      restart_policy:
        condition: on-failure

  # inference: 
  #   build: ./inference/
  #   environment:
  #     - PULSAR_HOST=pulsar
  #     - TOPIC_NAME=in
  #     - NAMESPACE_NAME=default
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
networks:
  default:
    driver: bridge